//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai7
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLD7Entities : DbContext
    {
        public QLD7Entities()
            : base("name=QLD7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbDiem> tbDiems { get; set; }
        public virtual DbSet<tbKhoa> tbKhoas { get; set; }
        public virtual DbSet<tbMonhoc> tbMonhocs { get; set; }
        public virtual DbSet<tbSinhVien> tbSinhViens { get; set; }
    }
}
