//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai7
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMonhoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbMonhoc()
        {
            this.tbDiems = new HashSet<tbDiem>();
        }
    
        public string Mamon { get; set; }
        public string Tenmon { get; set; }
        public string Makhoa { get; set; }
        public string Sohocphan { get; set; }
        public string Giaovien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDiem> tbDiems { get; set; }
    }
}
