//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai7
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbSinhVien()
        {
            this.tbDiems = new HashSet<tbDiem>();
        }
    
        public string MaSV { get; set; }
        public string Hoten { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Noisinh { get; set; }
        public string Gioitinh { get; set; }
        public string Diachi { get; set; }
        public string Makhoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbDiem> tbDiems { get; set; }
        public virtual tbKhoa tbKhoa { get; set; }
    }
}
