//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khachhang
    {
        public string MaKH { get; set; }
        public string Hoten { get; set; }
        public string SoCMND { get; set; }
        public Nullable<System.DateTime> Ngayden { get; set; }
        public string Maphong { get; set; }
        public Nullable<int> Songayo { get; set; }
        public Nullable<long> Thanhtien { get; set; }
    
        public virtual Phong Phong { get; set; }
    }
}
