//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai17
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diem
    {
        public string hocsinhID { get; set; }
        public Nullable<decimal> dienkt { get; set; }
        public string hanhkiem { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
    }
}
