//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bai17
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        public string hocsinhID { get; set; }
        public string lopID { get; set; }
        public string hoten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string diachi { get; set; }
        public string loptruong { get; set; }
        public string bithuchidoan { get; set; }
        public string ghichu { get; set; }
    
        public virtual Diem Diem { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
