//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayTinh
    {
        public string Somay { get; set; }
        public string HDD { get; set; }
        public string CPU { get; set; }
        public string RAM { get; set; }
        public string Sophong { get; set; }
    
        public virtual PhongMay PhongMay { get; set; }
    }
}
