//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLPMEntities : DbContext
    {
        public QLPMEntities()
            : base("name=QLPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MayTinh> MayTinhs { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<PhongMay> PhongMays { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThucHanh> ThucHanhs { get; set; }
    
        public virtual ObjectResult<tkslmtheophong_Result> tkslmtheophong()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<tkslmtheophong_Result>("tkslmtheophong");
        }
    }
}
