//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThucHanh
    {
        public string Sophong { get; set; }
        public string MaMH { get; set; }
        public Nullable<System.DateTime> NgayTH { get; set; }
        public string GiaovienTH { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual PhongMay PhongMay { get; set; }
    }
}
